In [122]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from scipy.io import loadmat
from sklearn.metrics import classification_report

data = loadmat(r'H:\吴恩达《机器学习》\andrew_ml_ex33507\ex3data1.mat')
data

X=data['X']
X=np.insert(X,0,np.ones(X.shape[0]),axis=1)
y=data['y']
theta=np.zeros((X.shape[1],10))
learning_rate=1

In [192]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def  cost(theta,X,y):
    y=np.mat(y).reshape(-1,1)
    theta=np.mat(theta).reshape(X.shape[1],-1)
    h=sigmoid(X@theta)
    return (-y.T@np.log(h)-(1-y).T@(np.log(1-h)))/len(X)

def gradient(theta,X,y):
    y=np.mat(y).reshape(-1,1)
    theta=np.mat(theta).reshape(X.shape[1],-1)
    return (sigmoid(X@theta)-y).T@X/len(X)

def costReg(theta, X, y, learningRate):
    X = np.matrix(X)
    theta=np.mat(theta).reshape(X.shape[1],-1)
    y = np.matrix(y)
    theta1=theta[1:,:]
    reg = (learningRate / (2 * len(X))) * (theta1.T@theta1)
    return cost(theta, X, y)+ reg

def gradientReg(theta, X, y, learningRate):
    X = np.matrix(X)
    theta=np.mat(theta).reshape(X.shape[1],-1)
    y = np.matrix(y)
    grad= np.zeros(theta.shape[1])
    grad=gradient(theta, X, y)+learningRate*(theta.T)/(len(X))
    grad[0,0]=np.sum(np.multiply(sigmoid(X * theta) - y, X[:,0])) / len(X)
    return grad.ravel()

def prediction(theta,X):
    X = np.matrix(X)
    theta=np.mat(theta).reshape(X.shape[1],-1)
    probability = sigmoid(X * theta)
    return [1 if x >= 0.5 else 0 for x in probability]

In [193]:
j=0
gradientReg(theta[:,j], X, y_i.iloc[:,0], 1)
# costReg(theta[:,j], X, y_i.iloc[:,0], 1).shape

matrix([[ 2.00000000e+03,  0.00000000e+00,  0.00000000e+00,
         -7.74530186e-08,  4.91729643e-07, -2.32940155e-07,
          5.96906573e-05,  6.01928054e-05,  1.15367732e-05,
          1.01547011e-05,  2.18079282e-05,  7.05070976e-06,
         -5.42333538e-06, -1.17534888e-05, -2.08794594e-05,
         -3.26743345e-05, -2.35833248e-05, -6.85661765e-06,
         -4.63698993e-08,  7.31889978e-08,  0.00000000e+00,
          2.46800109e-08, -2.10035403e-07,  1.03292772e-06,
         -1.85860754e-05, -3.20776025e-05,  8.42192691e-05,
          2.80642800e-04,  4.07120682e-04,  3.54123868e-04,
          1.34235160e-04, -5.08950044e-05, -1.06831626e-04,
         -1.21784484e-04, -1.44363715e-04, -4.72936666e-05,
         -4.81601477e-06, -2.55182972e-05, -2.70139653e-05,
         -3.89590142e-06, -8.85893246e-07, -2.11721903e-07,
          2.29617627e-06, -9.09571673e-06,  4.70609280e-05,
          4.06033842e-04,  1.41713054e-03,  2.42017046e-03,
          2.72592763e-03,  2.02847002e-0

In [194]:
opt.fmin_tnc(func=costReg, x0=np.zeros(X.shape[1]),fprime=gradientReg, args=(X, y_i.iloc[:,j], learning_rate))


(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [195]:
minimize(fun=costReg, x0=theta[:,j], args=(X, y_i.iloc[:,j], learning_rate), method='TNC', jac=gradientReg)

     fun: matrix([[-17.05142064]])
     jac: matrix([[ 2.00000000e+03,  0.00000000e+00,  0.00000000e+00,
         -7.74530186e-08,  4.91729643e-07, -2.32940155e-07,
          5.96906573e-05,  6.01928054e-05,  1.15367732e-05,
          1.01547011e-05,  2.18079282e-05,  7.05070976e-06,
         -5.42333538e-06, -1.17534888e-05, -2.08794594e-05,
         -3.26743345e-05, -2.35833248e-05, -6.85661765e-06,
         -4.63698993e-08,  7.31889978e-08,  0.00000000e+00,
          2.46800109e-08, -2.10035403e-07,  1.03292772e-06,
         -1.85860754e-05, -3.20776025e-05,  8.42192691e-05,
          2.80642800e-04,  4.07120682e-04,  3.54123868e-04,
          1.34235160e-04, -5.08950044e-05, -1.06831626e-04,
         -1.21784484e-04, -1.44363715e-04, -4.72936666e-05,
         -4.81601477e-06, -2.55182972e-05, -2.70139653e-05,
         -3.89590142e-06, -8.85893246e-07, -2.11721903e-07,
          2.29617627e-06, -9.09571673e-06,  4.70609280e-05,
          4.06033842e-04,  1.41713054e-03,  2.42017046e

In [179]:
from scipy.optimize import minimize
import scipy.optimize as opt

def one_vs_all(X,y,theta,learning_rate):
    X=np.mat(X)
    theta=np.mat(theta).reshape(X.shape[1],-1)
    y_i=pd.get_dummies(y.ravel(),prefix='y')
    y=np.mat(y).reshape(-1,1)
    for j in range(0,y_i.shape[1]):
        print('j=',j)
        fmin = minimize(fun=costReg, x0=theta[:,j], args=(X, y_i.iloc[:,j], learning_rate), method='TNC', jac=gradientReg)
        theta[:,j] = fmin.x.reshape(-1,1)
        print(np.sum(abs(prediction(theta[:,j],X)-y_i.iloc[:,j])))
    return theta

In [ ]:
fmin = minimize(fun=costReg, x0=theta[:,j], args=(X, y_i.iloc[:,j], learning_rate), method='TNC', jac=gradientReg)
theta[:,j] = fmin.x.reshape(-1,1)

In [180]:
tt=one_vs_all(X,y,theta,learning_rate)
tt


j= 0
4500
j= 1


F:\anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  
F:\anaconda3\envs\py37\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in matmul
  


305
j= 2
323
j= 3
305
j= 4
510
j= 5
4500
j= 6
4500
j= 7
411
j= 8
495
j= 9
4500


matrix([[ 0.00000000e+00, -1.10131264e+00, -1.03164314e+00, ...,
         -1.72236528e+00, -1.56710482e-01,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  8.92257028e-05, -9.35971403e-06, ...,
         -1.70068074e-05, -1.65786249e-06,  0.00000000e+00],
        [ 0.00000000e+00, -7.61813149e-06,  5.71290728e-07, ...,
          1.05490352e-06,  1.08760813e-07,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [82]:
theta=tt

In [37]:
def predict_all(X, theta):
    # convert to matrices
    X = np.matrix(X)
    theta = np.matrix(theta).reshape(X.shape[1],-1)
    
    # compute the class probability for each class on each training instance
    h = sigmoid(X *theta)
    
    # create array of the index with the maximum probability
    h_argmax = np.argmax(h, axis=1)
    
    # because our array was zero-indexed we need to add one for the true label prediction
    h_argmax = h_argmax + 1
    
    return h_argmax

In [84]:
y_pred = predict_all(X, theta)
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       500
           2       0.00      0.00      0.00       500
           3       0.00      0.00      0.00       500
           4       0.00      0.00      0.00       500
           5       0.00      0.00      0.00       500
           6       0.12      0.99      0.21       500
           7       0.00      0.00      0.00       500
           8       0.00      0.00      0.00       500
           9       0.00      0.00      0.00       500
          10       0.00      0.00      0.00       500

    accuracy                           0.10      5000
   macro avg       0.01      0.10      0.02      5000
weighted avg       0.01      0.10      0.02      5000



F:\anaconda3\envs\py37\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
